### ISSUE TITLE
[Unet3d] Prepare Datasets

### ISSUE THREAD

**Issue by lyly403** [ltechkorea/training_results_v1.1-pre#13]
Kits19 다운로드 완료

**Comment by lyly403** [comment]
#15

**Comment by lyly403** [comment]
**preprocessing data error**
```
Preprocessing raw-data-dir/kits19/data
Saving case_00000 shape (1, 190, 392, 392) mean [-2.] std [0.85]
Saving case_00001 shape (1, 188, 340, 340) mean [-1.82] std [0.94]
Traceback (most recent call last):
  File "preprocess_dataset.py", line 146, in <module>
    preprocessor.preprocess_dataset()
  File "preprocess_dataset.py", line 66, in preprocess_dataset
    image, label, image_spacings = self.load_pair(case)
  File "preprocess_dataset.py", line 90, in load_pair
    image, label = image.get_fdata().astype(np.float32), label.get_fdata().astype(np.uint8)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/dataobj_images.py", line 355, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/opt/conda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 332, in _get_unscaled
    return array_from_file(self._shape,
  File "/opt/conda/lib/python3.8/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/opt/conda/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/opt/conda/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/conda/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

```

대응방향 :

**Comment by lyly403** [comment]
완료.
