### ISSUE TITLE
[rnnt] prepare Dataset

### ISSUE THREAD

**Issue by lyly403** [ltechkorea/training_results_v1.1-pre#16]

**Comment by lyly403** [comment]
**preprocessing error**
```
$ bash scripts/download_librispeech.sh
Directory /opt/data/Dataset/training/LibriSpeech already exists.
sangwoo@ltech-gpu10:~/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch (ltech)
$ bash scripts/preprocess_librispeech.sh
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
Traceback (most recent call last):
  File "./utils/convert_librispeech.py", line 25, in <module>
    from preprocessing_utils import parallel_preprocess
  File "/home/sangwoo/training_results_v1.1-pre/LTechKorea/benchmarks/rnnt/implementations/pytorch/utils/preprocessing_utils.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
mkdir: cannot create directory ‘/sentencepieces’: Permission denied
scripts/create_sentencepieces.sh: line 18: jq: command not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sentencepiece'
cp: cannot stat 'librispeech1023.*': No such file or directory
Traceback (most recent call last):
  File "scripts/tokenize_transcripts.py", line 4, in <module>
    import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'

```

**Comment by jay-huh** [comment]
### Update `path` variables

- **`CHECKPOINT_DIR`은 사용하지 않는 것으로 보임. 일단은 놔둠.**

```
DATA_DIR="/opt/data/Dataset/training/rnnt"
CHECKPOINT_DIR="${DATA_DIR}/checkpoints"
RESULT_DIR="$PWD/results"
METADATA_DIR="${DATA_DIR}/tokenized"
SENTENCEPIECES_DIR="${DATA_DIR}/sentencepieces"
```

### Outputs

```bash
jay@ltech-gpu10 /opt/data/Dataset/training/rnnt
% ls -al
total 24
drwxrwsrwx  6 jay  ltech 4096 Sep  8 13:20 .
drwxrwsrwx  8 jay  ltech 4096 Sep  8 13:21 ..
drwxrwsrwx  2 jay  ltech 4096 Sep  8 13:10 checkpoints
drwxr-sr-x 16 root ltech 4096 Sep  8 15:05 LibriSpeech
drwxrwsrwx  2 jay  ltech 4096 Sep  8 15:06 sentencepieces
drwxrwsrwx  2 jay  ltech 4096 Sep  8 15:06 tokenized

jay@ltech-gpu10 /opt/data/Dataset/training/rnnt
% ls -alR checkpoints
checkpoints:
total 8
drwxrwsrwx 2 jay ltech 4096 Sep  8 13:10 .
drwxrwsrwx 6 jay ltech 4096 Sep  8 13:20 ..

jay@ltech-gpu10 /opt/data/Dataset/training/rnnt
% ls -alR ./sentencepieces
./sentencepieces:
total 276
drwxrwsrwx 2 jay  ltech   4096 Sep  8 15:06 .
drwxrwsrwx 6 jay  ltech   4096 Sep  8 13:20 ..
-rw-r--r-- 1 root ltech 253383 Sep  8 15:06 librispeech1023.model
-rw-r--r-- 1 root ltech  16653 Sep  8 15:06 librispeech1023.vocab

jay@ltech-gpu10 /opt/data/Dataset/training/rnnt
% ls -al tokenized
total 56748
drwxrwsrwx 2 jay  ltech     4096 Sep  8 15:06 .
drwxrwsrwx 6 jay  ltech     4096 Sep  8 13:20 ..
-rw-r--r-- 1 root ltech   396641 Sep  8 15:06 librispeech-dev-clean-wav-tokenized.pkl
-rw-r--r-- 1 root ltech   390248 Sep  8 15:06 librispeech-dev-other-wav-tokenized.pkl
-rw-r--r-- 1 root ltech   386927 Sep  8 15:06 librispeech-test-clean-wav-tokenized.pkl
-rw-r--r-- 1 root ltech   404229 Sep  8 15:06 librispeech-test-other-wav-tokenized.pkl
-rw-r--r-- 1 root ltech  5891381 Sep  8 15:06 librispeech-train-clean-100-wav-tokenized.pkl
-rw-r--r-- 1 root ltech 21452725 Sep  8 15:06 librispeech-train-clean-360-wav-tokenized.pkl
-rw-r--r-- 1 root ltech 29166364 Sep  8 15:06 librispeech-train-other-500-wav-tokenized.pkl



```
