### ISSUE TITLE
[resnet] data preprocessing 진행중

### ISSUE THREAD

**Issue by byounghak36** [ltechkorea/training_results_v1.1-pre#27]

**Comment by byounghak36** [comment]
```
root@129566f8bebe:~/resnet/tpu/tools/datasets# p0ython imagenet_to_gcs.py --raw_data_dir=/data/ --local_scratch_dir=/data/tf_records --nogcs_upload
bash: p0ython: command not found
root@129566f8bebe:~/resnet/tpu/tools/datasets# python imagenet_to_gcs.py --raw_data_dir=/data/ --local_scratch_dir=/data/tf_records --nogcs_upload
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/compat/v2_compat.py:111: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From imagenet_to_gcs.py:354: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
W0914 01:20:36.288848 139815663048512 deprecation.py:341] From imagenet_to_gcs.py:354: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Traceback (most recent call last):
  File "imagenet_to_gcs.py", line 470, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "imagenet_to_gcs.py", line 460, in main
    run(raw_data_dir=FLAGS.raw_data_dir,
  File "imagenet_to_gcs.py", line 446, in run
    training_records, validation_records = convert_to_tf_records(
  File "imagenet_to_gcs.py", line 354, in convert_to_tf_records
    validation_synsets = tf.gfile.FastGFile(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: /data/synset_labels.txt; No such file or directory
root@129566f8bebe:~/resnet/tpu/tools/datasets#
```

syntext label 이 필요하다가 에러발생, 추가 예정

**Comment by byounghak36** [comment]
https://cloud.google.com/tpu/docs/imagenet-setup?hl=zh-tw

위 사이트에 적힌 메뉴얼대로
```
wget -O $IMAGENET_HOME/synset_labels.txt \
https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/imagenet_2012_validation_synset_labels.txt
```
명렁어를 사용해 보았지만 아래와 같이 에러발생

```
wget -O /opt/data/Dataset/imn/synset_labels.txt \
https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/imagenet_2012_validation_synset_labels.txt
--2021-09-14 10:34:21--  https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/imagenet_2012_validation_synset_labels.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-14 10:34:21 ERROR 404: Not Found.
```

**Comment by byounghak36** [comment]
https://goodtogreate.tistory.com/entry/MLPerf
위 링크 설명을 따라 진행중

**Comment by byounghak36** [comment]
https://raw.githubusercontent.com/tensorflow/models/master/research/slim/datasets/imagenet_2012_validation_synset_labels.txt

synset_label 경로가 위 링크로 바뀐것으로 보임, 링크에서 다운로드하고 데이더 전처리 진행중.

**Comment by byounghak36** [comment]
전처리 정상적으로 완료, 벤치마크 실행함
